#!/bin/sh
# user dependent .bashrc file

##. "${HOME}/app/sec/env"

# if not running interactively, 
#  only read secure data into environment
echo "$-" | grep -q 'i' || exit 1

env | grep -q -E '^SSH_*' && export SSH=1 || export SSH=0

# override path by user and setup executeables
#PATH="${PATH}:${HOME}/usr/prj/shl/void/bin:${HOME}/usr/prj/shl/sirc:${HOME}/bin"

printf '' > "${HOME}/.bash_login"

#eval $(dircolors -b $HOME/.dircolors)

printf '[%s] Loading configs ...\n' "$(date +'%X')" | tee -a "${HOME}/.bash_login"
for p in "${HOME}/app/cnf/bash/run/"* ; do
  if [[ -x "${p}" ]]; then
    bn=$(basename "${p}" | cut -d '_' -f 2)
    printf '[%s] Sourcing %s ...\n' "$(date +'%X')" "${bn}" | tee -a "${HOME}/.bash_login"
    . "${p}"
  fi
done

. ~/app/cnf/shell/profile

$WELCOME_COMMAND
