#!/usr/bin/env sh

dir=$(dirname $(realpath -P "$0"))
name=$(basename $0)

xinit() {
  printf '[%s] Starting X login ...\n' "$(date +'%X')"

  if test -z "${STP_NAME}"; then
    printf '[%s] ERROR: Please set ${%s}!\n' "$(date +'%X')" 'STP_NAME'
    return 1
  fi

  if ! test -d "${dir}/setups/${STP_NAME}"; then
    printf '[%s] ERROR: Directory setups/%s not found!\n' "$(date +'%X')" "${STP_NAME}"
    return 1
  fi

  printf '[%s] Setting current link ...\n' "$(date +'%X')"
  if test -z "${DRY_RUN}"; then
    test -e "${dir}/setups/current" && rm -f "${dir}/setups/current"
    ln -s "${dir}/setups/${STP_NAME}" "${dir}/setups/current"
  fi

  if test -d "${dir}/setups/${STP_NAME}/exe"; then
    printf '[%s] Adding stp to ${PATH} ...\n' "$(date +'%X')"
    test -z "${DRY_RUN}"  && export PATH="${PATH}:${dir}/setups/${STP_NAME}/exe"
  fi

  printf '[%s] Adding thm to ${PATH} ...\n' "$(date +'%X')"
  test -z "${DRY_RUN}"  && export PATH="${PATH}:${HOME}/usr/prj/shl/void/thm:${HOME}/usr/prj/shl/void/thm/bin"

  printf '[%s] Loading theme ...\n' "$(date +'%X')"
  if test -z "${DRY_RUN}"; then
    test "${THM_NAME}" = 'rnd' && export THM_NAME=$(thm r)
    thm l
  fi
  
  if test -f "${dir}/setups/${STP_NAME}/conf"; then
    printf '[%s] Reading config ...\n' "$(date +'%X')" 
    test -z "${DRY_RUN}"  && . "${dir}/setups/${STP_NAME}/conf"
  fi

  if test -f "${dir}/setups/${STP_NAME}/init"; then
    printf '[%s] Starting init ...\n' "$(date +'%X')" 
    test -z "${DRY_RUN}"  && . "${dir}/setups/${STP_NAME}/init"
  fi

  if test -d "${dir}/setups/${STP_NAME}/run"; then
    printf '[%s] Starting apps ...\n' "$(date +'%X')"
    for app in "${dir}/setups/${STP_NAME}/run/"* ; do
      if test -x "${app}"; then
        bn=$(basename "${app}" | cut -d '_' -f 2)
        printf '[%s] - %s\n' "$(date +'%X')" "${bn}" 
        test -z "${DRY_RUN}"  && "${app}"
      fi
    done
  fi

  if test -e "${HOME}/.Xresources"; then
    printf '[%s] Merging X resources ...\n' "$(date +'%X')"
    test -z "${DRY_RUN}"  && xrdb -merge "${HOME}/.Xresources"
  fi

  printf '[%s] Running X loop ...\n' "$(date +'%X')"
  test -z "${DRY_RUN}"  && "${dir}/xloop"

  if test -f "${dir}/setups/${STP_NAME}/clean"; then
    printf '[%s] Cleaning up ...\n' "$(date +'%X')" 
    test -z "${DRY_RUN}"  && . "${dir}/setups/${STP_NAME}/clean"
  fi
  
  printf '[%s] Shutting down ...\n' "$(date +'%X')"
}

xinit
