#!/usr/bin/env sh

#dir=$(dirname $(realpath -P "$0"))
dir="${HOME}/usr/prj/shl/void/thm"

if ! test -e "${dir}/themes/${THM_NAME}"; then
  >&2 printf '[%s] ERROR: Theme %s not found!\n' "$(date +'%X')" "${THM_NAME}"
  exit 1
fi

cd "${dir}/themes/${THM_NAME}"

export variant=$(cat variant)
export base00=$(sed -n '1p' "shades.list")
export base01=$(sed -n '2p' "shades.list")
export base02=$(sed -n '3p' "shades.list")
export base03=$(sed -n '4p' "shades.list")
export base04=$(sed -n '5p' "shades.list")
export base05=$(sed -n '6p' "shades.list")
export base06=$(sed -n '7p' "shades.list")
export base07=$(sed -n '8p' "shades.list")

if test "${variant}" = 'light'; then
  export base08=$(sed -n '3p' "colors.list")
  export base09=$(sed -n '4p' "colors.list")
  export base0A=$(sed -n '5p' "colors.list")
  export base0B=$(sed -n '3p' "colors.list")
  export base0C=$(sed -n '4p' "colors.list")
  export base0D=$(sed -n '5p' "colors.list")
  export base0E=$(sed -n '6p' "colors.list")
  export base0F=$(sed -n '8p' "colors.list")
else
  export base08=$(sed -n '5p' "colors.list")
  export base09=$(sed -n '4p' "colors.list")
  export base0A=$(sed -n '3p' "colors.list")
  export base0B=$(sed -n '5p' "colors.list")
  export base0C=$(sed -n '4p' "colors.list")
  export base0D=$(sed -n '3p' "colors.list")
  export base0E=$(sed -n '6p' "colors.list")
  export base0F=$(sed -n '8p' "colors.list")
fi

export wallpaper=$(find -type f -name 'wall.*' -printf "${PWD}/%P" | head -1)
export thumbnail=$(find -type f -name 'thumb.*' -printf "${PWD}/%P" | head -1)

if test -f 'fonts.list'; then
  norm=$(sed '1q;d' 'fonts.list')
  mono=$(sed '2q;d' 'fonts.list')
  symb=$(sed '3q;d' 'fonts.list')
  export fontName="$(echo "${norm}" | cut -d ':' -f 1)"
  export fontSize="$(echo "${norm}" | cut -d ':' -f 2)"
  export monoName="$(echo "${mono}" | cut -d ':' -f 1)"
  export monoSize="$(echo "${mono}" | cut -d ':' -f 2)"
  export symbName="$(echo "${symb}" | cut -d ':' -f 1)"
  export symbSize="$(echo "${symb}" | cut -d ':' -f 2)"
else
  export fontName='Ubuntu'
  export fontSize='12'
  export monoName='Ubuntu Mono'
  export monoSize='12'
  export symbName='Font Awesome 5 Free'
  export symbSize='12'
fi

cd - >/dev/null
