#!/usr/bin/env sh

cat << EOL
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>This blog</strong> was generated by <strong>mkws</strong>
        which was created by <a href="github.com/Anachron">Anachron</a>.
      </p>
    </div>
  </div>
</footer>
EOL
