#!/usr/bin/env sh

colors="${COLORS:-8}"
TMP_DIR="${TMP_DIR:-tmp}"

if test -z "${UNSPLASH_API}"; then
  >&2 printf '[%s] [ERROR]: Please set ${%s}!\n' "$(date +'%X')" 'UNSPLASH_API'
  exit 1
fi

res=$(xrandr | grep -o -E 'primary [0-9]*x[0-9]*' | grep -o -E '[0-9x]*')
imw=$(echo "${res}" | awk -F 'x' '{print $1}')
imh=$(echo "${res}" | awk -F 'x' '{print $2}')

api="https://api.unsplash.com/photos/random/?w=${imw}&h=${imh}"
rnd=$(curl -s "${api}" -H "Authorization: Client-ID ${UNSPLASH_API}")

url=$(printf '%s' "${rnd}" | jq ".urls.custom" | tr -d '"')
id=$(printf '%s' "${rnd}" | jq ".id" | tr -d '"')
fmt=$(printf '%s' "${url}" | grep -o -E 'fm=([a-z])*' | cut -d '=' -f 2)
img="${TMP_DIR}/unsplash-${id}.${fmt}"

test -f "${img}" || curl -s "${url}" > "${img}"

convert "${img}" +dither -colors "${colors}" -define histogram:unique-colors=true -format "%c" histogram:info: | grep -o -E '#[0-9A-F]*' > "${TMP_DIR}/colors.list"
bn=$(basename "${img}" | cut -d '.' -f 1)
export THEME_NAME="${bn}"
export THEME_COLORS="$(cat ${TMP_DIR}/colors.list)"
export THEME_IMAGE=$(realpath "${img}")
rm "${TMP_DIR}/colors.list"
