#!/usr/bin/env sh

chc=$(printf 'exec\npass\nmovie\nsteam\nwine\n' | run-menu ${@})

case "${chc}" in
  exec) launch-menu;;
  movie) movie-menu;;
  pass) pass-menu;;
  steam) steam-menu;;
  wine) wine-menu;;
esac
