#!/usr/bin/env sh

#cmd=$("${SHELL}" -c 'compgen -c | sort -u' | run-menu)
cmd=$(printf 'firefox\nhedgewars\nlxappearance\nlutris\nminecraft\nsteam\nzathura' | run-menu)
#tf=$(mktemp "/tmp/${cmd}-XXXXXX.log")
tf='/dev/null'
test -n "${cmd}" && "${SHELL}" -c "${cmd}" 2>&1 >"${tf}"
