#!/usr/bin/env sh

txt=''

export NOTIFY_HISTORY='/tmp/notify-history'

# NOTIFY_ABBREV, NOTIFY_ICON, NOTIFY_NAME, NOTIFY_TEXT, NOTIFY_PRIO

test -n "${NOTIFY_ICON}" && txt="${NOTIFY_ICON} "
test -n "${NOTIFY_TEXT}" && txt="${txt}${NOTIFY_TEXT} "

notify-send -a "${NOTIFY_NAME}" -u "${NOTIFY_PRIO:-low}" "${txt}"

printf '%s|%s|%s|%s|%s\n' "$(date +'%s')" "${NOTIFY_NAME}" "${NOTIFY_ICON}" "${NOTIFY_TEXT}" "${NOTIFY_PRIO}" >> "${NOTIFY_HISTORY}"
