#!/usr/bin/env sh

tf=$(mktemp '/tmp/colors-XXXXX')

trap "rm ${tf}" EXIT INT TERM

rgb2hex() {
  printf '#%02X%02X%02X' "${1}" "${2}" "${3}"
}

json2rgb() {
  jq -c '.[]' | sed 's|^\[\[||g;' | tr '[' '\n' | tr -d ']' | sed 's|,$||g; s|,| |g'
}

# get random color palette (5)
col=$(curl -s 'http://colormind.io/api/' --data-binary '{"model":"default"}')
rgb=$(printf '%s\n' "${col}" | json2rgb)

# convert them to hex colors
printf '%s\n' "${rgb}" | while read line; do
  printf '%s\n' $(rgb2hex ${line})
done | head -n 4 >> "${tf}"

fc=$(printf '%s\n' "${rgb}" | sed -n '1p')
lc=$(printf '%s\n' "${rgb}" | sed -n '5p')

fn=$(printf '%s' "${fc}" |  tr ' ' ',')
ln=$(printf '%s' "${lc}" |  tr ' ' ',')

lst="[${ln}],\"N\",\"N\",\"N\",[${fn}]"
data='{"model":"default", "input": ['"${lst}"']}'
col=$(curl -s 'http://colormind.io/api/' --data-binary "${data}")
rgb=$(printf '%s\n' "${col}" | json2rgb)

# convert them to hex colors
printf '%s\n' "${rgb}" | while read line; do
  printf '%s\n' $(rgb2hex ${line})
done | head -n 4 >> "${tf}"

cat "${tf}"
rm "${tf}"
