#!/usr/bin/env sh

xpmFile="/tmp/power.state"

test "$#" -eq 1 || exit 1

 # already one action in progress
test "${1}" != 'a' && test -f "${xpmFile}" && exit 1

case "${1}" in
  p)
    test -f "${xpmFile}" || exit 1
    notify-send ' abort'
    rm "${xpmFile}"
    exit 0
    ;;
  h) notify-send ' sleep';;
  k) notify-send ' lock';;
  l) notify-send ' logoff';;
  n) notify-send ' shutdown';;
  o) notify-send ' reboot';;
  *) exit 1;; # unknown command
esac

printf '%s' "${1}" > "${xpmFile}"

sleep 3.

test -f "${xpmFile}" || exit 0 # user aborted

rm "${xpmFile}"

case "${1}" in
  h) sudo zzz;;
  k) physlock -m;;
  #k) . /etc/os-release; physlock -p "You are currently logged as ${USER} into ${NAME}";;
  #k) slock;;
  l) pkill -f xinit;;
  n) sudo shutdown -P now;;
  o) sudo reboot;;
esac
