#!/usr/bin/env sh

xset +fp ~/.fonts # more fonts
xset fp rehash # reload fonts
xset -dpms # disable screen lock
#xset dpms 600 1200 0 # enable screen power modus
xsetroot -cursor_name left_ptr # set default cursor
xset m 3/2 0 # manage mouse speed

run-jobs    # background-jobs
cwm         # window manager  : ~/.cwmrc
stop-jobs   # background-jobs
