#!/bin/env sh

fp="${HOME}/usr/med/img/scr/$(date +'%x-%X')"

if test "${1}" = 'area'; then
  maim -s -c 0.1,0.05,0.3,1 "${fp}-area.png"
elif test "${1}" = 'window'; then
  fp="${fp}-window.png"
  import -w $(gfcw) "${fp}"
elif test "${1}" = 'desktop'; then
  fp="${fp}-desk.png"
  import -w root "${fp}"
fi

test $? -eq 0 && printf '%s' "${fp}" && notify-quick ' ' 'Screenshot' "${1}" 'low'
