#!/usr/bin/env sh

test "$#" -eq 2 || exit 1

export STATUS_DATA='/tmp/status-data'

grep -q "^${1}" "${STATUS_DATA}" \
  && sed -i "s/^${1}.*/${1}|${2}/" "${STATUS_DATA}" \
  || printf '%s|%s\n' "${1}" "${2}" >> "${STATUS_DATA}"
