#!/usr/bin/env sh

game=$(printf 'DotA\nN++\n' | run-menu -l 50)

test -z "${game}" && exit

case "${game}" in
  'DotA') DRI_PRIME=1 steam steam://run/570;;
  'N++') DRI_PRIME=1 steam steam://run/230270;;
esac

