#!/usr/bin/env sh

unset WALLPAPER
unset PALETTE

while test "$#" -gt 0; do
  if test -f "${1}"; then
    ft=$(file "${1}" | grep -o -E 'text|image')
    test "${ft}" = 'image' && export WALLPAPER=$(realpath "${1}")
    test "${ft}" = 'text' && export PALETTE=$(realpath "${1}")
  fi
  shift 1
done

if test -z "${WALLPAPER}${PALETTE}"; then
  r=$(shuf -i0-1 -n1)
  test "${r}" -eq 0 && export PALETTE=$(find "${HOME}/usr/col/" -maxdepth 2 -type f | sort -R | head -n 1)
  test "${r}" -eq 1 && export WALLPAPER=$(find "${HOME}/usr/med/img/wpr" -maxdepth 1 -type f | sort -R | head -n 1)
fi

#printf '\nWALL: "%s"\nPALL: "%s"\n\n' "${WALLPAPER}" "${PALETTE}"

pal-change
wal-change

thm-generate
. thm-palette

thm-apply xrs # apply theme to xrs
. thm-export
thm-apply cnf # apply theme to config
thm-apply gtk # apply theme to gtk

#cat /tmp/theme | gen-palette # generate palette

thm-reload
