#!/usr/bin/env sh

pgrep dunst >/dev/null && pkill dunst

dunst &       # notifications   : ~/.config/dunst/dunstrc
pgrep cwm 2>&1 >/dev/null && kill -HUP $(pgrep cwm) # reload cwm config
#tmux source-file ~/.tmux.conf # reload tmux

xrdb -load ~/.Xresources # reload xrs
. thm-export
thm-apply sh # reload all terminals

status-runner & # reload statusbar
syswatch-runner & # reload syswatch
