#!/usr/bin/env sh

wc="${WALLPAPER:-/tmp/wallcolor.png}"
wr='/tmp/wall-resized'
w1='/tmp/wall-1x1'

if test -f "${WALLPAPER}"; then
  w=$(convert "${WALLPAPER}" -format "%w" info:)
else
  w=50
  c=$(cat "${PALETTE}" | head -n 1)
  bg=$(printf '%s\n' "${c}" | head -n 1)
  printf '%s\n' "${bg}" | pal-generate "${wc}"
fi

convert "${wc}" -crop "${w}x50+0+0" +repage "${wr}"
convert "${wr}" -resize 1x1! "${w1}"

m=$(convert "${w1}" -format "%[fx:mean]" info:)
b=$(echo "scale=0; ${m} * 100 / 1" | bc -s)

printf '%s' "${b}" > /tmp/status-brightness

rm "${wr}" "${w1}"
