#!/usr/bin/env sh

while read f; do
  a=$(realpath "${f}")
  b=$(basename "${a}")
  d=$(dirname "${a}")
  file "${a}" | grep -q 'text' || continue
  printf 'Creating palette for "%s"\n' "${b}"
  mkdir -p "${d}/prv"
  test -f "${d}/prv/${b}.png" && continue
  cat "${a}" | pal-preview "${d}/prv/${b}.png"
done
