#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Backup'
export STATUS_VALUE=$(pgrep borg 2>&1 >/dev/null && printf 1 || printf 0)
export STATUS_TEXT=$(test "${STATUS_VALUE}" -eq 1 && printf 'run.' || printf 'none')
export STATUS_URGENT="${STATUS_VALUE}"
export STATUS_PERIOD=30
