#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='CPU Usage'
export STATUS_VALUE=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf "%3.0f\n", usage}' | xargs)
export STATUS_TEXT="${STATUS_VALUE}%"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -ge 50 && printf 1 || printf 0)
export STATUS_PERIOD=5
