#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Firewall'
export STATUS_VALUE=$(pgrep -f ^ufw > /dev/null && printf 'on' || printf 'off')
export STATUS_TEXT="${STATUS_VALUE}"
export STATUS_URGENT=$(test "${STATUS_VALUE}" = 'off' && printf 1 || printf 0)
export STATUS_PERIOD=5
