#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='GPU Temp'
export STATUS_VALUE=$(sensors | grep 'GPU' | awk '{print $1$2" "$3}' | tr -d '+' | grep -o -E '[0-9]{2,3}' | tr '\n' ' ')
export STATUS_TEXT="${STATUS_VALUE}°C"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -gt 60 && printf 1 || printf 0)
export STATUS_PERIOD=5
