#!/usr/bin/env sh

today=$(date +%s)
holiday=$(date -d "2019-05-30" +%s)
diff=$(echo "(${holiday} - ${today}) / 86400" | bc -s)

export STATUS_ICON=' '
export STATUS_NAME='Holiday'
export STATUS_VALUE="${diff}"
export STATUS_TEXT="${STATUS_VALUE} days"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -le 30 && printf 1 || printf 0)
export STATUS_PERIOD=600
