#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Updates'
export STATUS_VALUE=$(xbps-install -Mun | wc -l)
export STATUS_TEXT="${STATUS_VALUE}"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -ge 10 && printf 1 || printf 0)
export STATUS_PERIOD=60
