#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Redshift'
export STATUS_VALUE=$(pgrep redshift > /dev/null && printf 0 || printf 1)
export STATUS_TEXT=$(test "${STATUS_VALUE}" -eq 1 && printf 'off' || printf 'on')
export STATUS_URGENT=$(test "${STATUS_VALUE}" -eq 1 && printf 1 || printf 0)
export STATUS_PERIOD=30
