#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Download'

WLAN_DEV=$(iw dev | awk '$1 == "Interface" {print $2}')

R1=$(cat "/sys/class/net/${WLAN_DEV}/statistics/rx_bytes")
sleep 1
R2=$(cat "/sys/class/net/${WLAN_DEV}/statistics/rx_bytes")

RBPS=$(expr $R2 - $R1)
RKBPS=$(expr $RBPS / 1024)

#printf '%s' "${RKBPS}"
export STATUS_VALUE="${RKBPS}"
export STATUS_TEXT="${STATUS_VALUE}"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -ge 1000 && printf 1 || printf 0)
export STATUS_PERIOD=10
