#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Samba'
export STATUS_VALUE=$(smbstatus -b 2>/dev/null | awk 'match($1,"[0-9]") {print $0}' | wc -l)
export STATUS_TEXT="${STATUS_VALUE}"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -gt 0 && printf 1 || printf 0)
export STATUS_PERIOD=10
