#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='SSH in'
export STATUS_VALUE=$(who | grep pts | wc -l)
export STATUS_TEXT="${STATUS_VALUE}"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -gt 0 && printf 1 || printf 0)
export STATUS_PERIOD=5
