#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Screenshare'
export STATUS_VALUE=$(test -e /tmp/ffserver.conf && printf 1 || printf 0)
export STATUS_TEXT=$(test "${STATUS_VALUE}" -eq 1 && printf 'on' || printf 'off')
export STATUS_URGENT=$(test "${STATUS_VALUE}" -eq 1 && printf 1 || printf 0)
export STATUS_PERIOD=5
