#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Swap'
export STATUS_VALUE=$(cat /proc/swaps | tail -n 1 | awk '{print "("$4" * 100) / "$3}' | bc -s)
export STATUS_TEXT="${STATUS_VALUE}%"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -ge 20 && printf 1 || printf 0)
export STATUS_PERIOD=15
