#!/usr/bin/env sh

export STATUS_ICON=' '
export STATUS_NAME='Trash'
export STATUS_VALUE=$(trash-lst | wc -l)
export STATUS_TEXT="${STATUS_VALUE}"
export STATUS_URGENT=$(test "${STATUS_VALUE}" -gt 100 && printf 1 || printf 0)
export STATUS_PERIOD=60
