#!/usr/bin/env sh

. ~/app/cnf/shell/env # load env
. ~/app/sec/shell/env # load secure env

. ~/app/cnf/shell/hist # shell history

. ~/app/cnf/shell/defs # load defaults
. ~/app/cnf/shell/paths # load paths

# skip remaining actions
# if not run interactively
echo "$-" | grep -q 'i' || exit 0

. ~/app/cnf/shell/aliases
. ~/app/cnf/shell/funcs

#. ~/bin/ji # directory switcher
#. ~/bin/de # .env file handler
#. ~/bin/qh # quick history

. ~/app/cnf/shell/vars

if command -v hist; then
  hist dc # empty tty dir history
fi
#hist cc # empty tty cmd history

command -v thm-apply && thm-apply sh $(tty) # apply shell colors
test -e ~/.dircolors && eval $(dircolors -b $HOME/.dircolors) # apply dir colors
