#!/usr/bin/env sh

. irc-utils || exit 2

test "$#" -le 1 && printf 'To less arguments!\n' && exit 1

readServ $(findServ "${1}")

test -z "${s_key}" && printf 'Unknown server: %s\n' "${1}" && exit 1

case "${2}" in
  a|archive)
    shift 2
    saveHistory "${@}"
    ;;
  b|bot)
    readIdent $(findServIdents "${1}") || exit 1
    readChan $(findChan "${1}" "${3}") || exit 2
    command -v "${4}" 2>&1 >/dev/null || exit 3
    export BOT="${4}"
    runBot
    ;;
  c|con)
    readIdent $(findServIdents "${1}") || exit 1
    joinServ || exit 1
    ;;
  g|log)
    readChan $(findChan "${1}" "${3}") || exit 1
    "${EDITOR:-vim}" "${datDir}/${s_addr}/${c_name}/out"
    ;;
  h|hist)
    readChan $(findChan "${1}" "${3}") || exit 1
    shift 3
    findHistory "${@}"
    ;;
  i|ign) isIgnored "${1}" "${3}";;
  j|join)
    readChan $(findChan "${1}" "${3}") || exit 1
    joinChan
    ;;
  l|leave)
    readChan $(findChan "${1}" "${3}") || exit 1
    leaveChan
    ;;
  n|nicks)
    t=$(tac "${datDir}/${s_addr}/out" | grep -m 1 "= ${chn}" | cut -d ' ' -f 1)
    tac "${datDir}/${s_addr}/out" | grep "${t} = ${chn}" | cut -d ' ' -f 4- | tr ' ' '\n' | sort -u
    ;;
  o|open)
    if tmux ls | grep -q "irc-${1}-${3}"; then
      tmux attach -t "irc-${1}-${3}"
    else
      tmux \
        new-session "irc ${1} tr ${3}" \; \
        split-window -f -l 2 "irc ${1} tw ${3}" \; \
        rename-session "irc-${1}-${3}" \;
#        split-window -h -p 30 "irc ${1} n ${3} | less" \; \
    fi
    ;;
  r|rec)
    readIdent $(findServIdents "${1}") || exit 1
    recServ
    ;;
  tr|termreader)
    readChan $(findChan "${1}" "${3}") || exit 1
    readIdent $(findServIdents "${1}") || exit 1
    shift 3
    termReader "${@}"
    ;;
  tw|termwriter)
    readChan $(findChan "${1}" "${3}") || exit 1
    readIdent $(findServIdents "${1}") || exit 1
    shift 3
    termWriter "${@}"
    ;;
  w|write)
    readChan $(findChan "${1}" "${3}") || exit 1
    shift 3
    writeChan "${@}"
    ;; 
  q|quit)
    pid=$(cat "${datDir}/${s_addr}/pid")
    ps -p "${pid}" 2>&1 >/dev/null || exit
    sess=$(tmux ls 2>/dev/null | grep -o -w -E "irc-${s_key}-[a-z]*")
    if test -n "${sess}"; then
      for s in ${sess}; do
        tmux kill-session -t "${s}"
      done
    fi
    printf '/quit\n' > "${datDir}/${s_addr}/in"
    tail --pid="${pid}" -f /dev/null
    printf 'Disconnected\n'
    ;;
esac
