#!/usr/bin/env sh

acl=$(find "${HOME}/app/sec/getmail" -type f -name '*.rc' | sort)
for f in ${acl}; do
  acc=$(basename "${f}" | cut -d '.' -f 1)
  printf '[%s] Updating %s\n' "$(date +'%X')" "${acc}"
  getmail -q -n -r"${f}"
  new=$(find "${HOME}/usr/mls/${acc}/INBOX/new" -type f | wc -l)
  minc "${HOME}/usr/mls/${acc}/INBOX"
  test "${new}" -gt 0 && printf 'MI|%s\n' "${acc}" > /tmp/status-fifo || true
done
