#!/usr/bin/env sh

if test "$#" -gt 0; then
  MAIL_ACC="${1}"
else
  MAIL_ACC=$(grep -B 3 'from[ ]*'"$(mfrom)" ~/.msmtprc | head -n 1 | awk '{print $2}')
fi

cat "${HOME}/usr/mls/${MAIL_ACC}/all.seq" | mscan
