#!/usr/bin/env sh

n=1
#MAIL_ACC="gmx-prv"

while test "$#" -gt 0; do 
  if test -e "${HOME}/usr/mls/${1}"; then
    MAIL_ACC="${1}"
  elif test "${1}" -gt 0 2>&1 >/dev/null; then
    n="${1}"
  fi
  shift
done

test -z "${MAIL_ACC}" && MAIL_ACC=$(grep -B 3 'from[ ]*'"$(mfrom)" ~/.msmtprc | head -n 1 | awk '{print $2}')
mlist "${HOME}/usr/mls/${MAIL_ACC}/INBOX/cur" | msort -r -d | mpick "1:${n}"
