#!/usr/bin/env sh

fn="${1}"
ff=$(find ~/app/dat/x/fonts -iname "*${fn}*-[rR]egular.ttf")
fp="/tmp/font-prv.html"

cat > "${fp}" <<EOL
<html>
  <head>
  <title>Font Preview: ${fn}</title>
  <style type="text/css">
    @font-face {font-family: '${fn}'; src: url('${ff}');}
    body {font-family: '${fn}';}
  </style>
  </head>
  <body>
    <p>The quick brown fox jumps over the lazy dog</p>
    <p>0123456789</p>
    <p>.,-+*#'_</p>
  </body>
</html>
EOL

firefox "${fp}"
#rm "${fp}"
