#!/usr/bin/env sh

tgt="${1:-jpg}"
args="-c -w -h -b 1.5"

while read f; do
  printf '%s' "${f}" | grep -q -E 'CR2$' || continue
  n=$(printf '%s' "${f}" | sed "s/CR2$/${tgt}/g")
  printf 'Converting "%s" to "%s" ...\n' "${f}" "${n}"
  if test "${tgt}" = "jpg"; then
    dcraw ${args} "${f}" | pnmtojpeg > "${n}"
  elif test "${tgt}" = "png"; then
    dcraw ${args} "${f}" | pnmtopng > "${n}"
  fi
done
