#!/bin/sh
# Easy file trasher
# 
# Usage: trash [a] <file1> [<file2>] (or use stdin) to add to trash
#        trash r <pattern>] to restore
#        trash l [<pattern>] to list all trashed files (with pattern)
#        trash c [<days>] to clean the trash (default 30 days old)
td="${HOME}/usr/tmp/trash"

if test "$#" -eq 0; then
  1>&2 cat << EOL
  $(basename "$0"): file/dir trasher

  commands
    a:  Add file/directory to trash
    c:  Clear trash (default age >= 30 days)
    i:  Get information of trashed item
    l:  List all trashed items
    r:  Ressurect delete item(s)
EOL
  exit 1
fi

if printf 'ciklrt' | grep -F -q "${1}"; then
  a="${1}"
  shift
else
  a='a'
fi

test ! -d "${td}" && mkdir -p "${td}" && chown "${USER}" "${td}"
test -p /dev/stdin && files=$(cat) || files="${@}"

case "${a}" in
  a)
    for f in ${files}; do
      test ! -e "${f}" && continue
      rp=$(readlink -f "${f}")
      echo "${rp}" | grep -q "${td}" && continue
      mt=$(stat -c '%Y' "${rp}")
      test -f "${f}" && ms=$(md5sum "${rp}" | awk '{print $1}')
      test -d "${f}" && ms=$(tar -cf - "${rp}" 2>&1 >/dev/null | md5sum | awk '{print $1}')
      bn=$(basename "${rp}")
      tn="${bn}@${ms}.dat"
      nf="${bn}@${ms}.inf"
      if mv "${rp}" "${td}/${tn}"; then
        printf "%s\n%s\n" "${rp}" "${mt}" > "${td}/${nf}"
        touch "${td}/${tn}" "${td}/${nf}"
        printf 'Trashed: %s\n' "${td}/${bn}@${ms}.{dat,inf}"
      fi
    done
    exit
  ;;
  c)
    find "${td}" -mtime +"${1:-30}" -exec rm -rf {} \;
  ;;
  i)
    cat "${td}/${1}.inf" | sed '1 s|^|Source:\t|; 2 s|^|Date:\t|'
    #test ! -z "${1}" && p="${1}" || p='*'
    #find "${td}" -mindepth 1 -maxdepth 1 -name "${p}" -not -name '*.dat' -exec head -n 1 {} \;
  ;;
  l)
    test ! -z "${1}" && p="${1}" || p='*'
    find "${td}" -mindepth 1 -maxdepth 1 -printf '%P\n' | grep -E "${p}" | grep -E '*.inf' | sed 's/.inf//g'
  ;;
  r)
    files=$(find "${td}" -name "*${1}*" -and -name "*.dat")
    for f in ${files}; do
      nf=$(printf '%s' "${f}" | sed 's|.dat$|.inf|g')
      rp=$(sed -n '1p' "${nf}")
      mt=$(sed -n '2p' "${nf}")
      if mv "${f}" "${rp}"; then
        touch -d "@${mt}" "${rp}"
        printf 'Restored: %s\n' "${rp}"
        rm "${nf}"
      fi
    done
  ;;
esac
