#!/usr/bin/env sh

w=$(which "${1}" 2>/dev/null)
if test -z "${w}"; then
  2>&1 printf 'Error: %s could not be found.\n' "${1}"
  exit 1
fi

f=$(file "${w}")
if ! printf '%s' "${f}" | grep -q "text"; then
  2>&1 printf 'Error: %s is not a text-file.\n' "${w}"
  exit 1
fi

vim "${w}"
