" plugins
call plug#begin('~/.vim/plugged')
Plug 'rust-lang/rust.vim'
call plug#end()

" look & feel
set nowrap
syntax on
colorscheme term

" indention
" filetype plugin indent on
set tabstop=2       "show existing tab with x spaces width
set expandtab       "Use softtabstop spaces instead of tab characters for indentation
set shiftwidth=2    "Indent by x spaces when using >>, <<, == etc.
set softtabstop=2   "Indent by x spaces when pressing <TAB>

"set autoindent      "Keep indentation from previous line
"set smartindent     "Automatically inserts indentation in some cases
"set cindent         "Like smartindent, but stricter and more customisable
