#!/usr/bin/env sh

temps=$(sensors | grep 'Core' | awk '{print $1$2" "$3}' | tr -d '+' | grep -o -E '[0-9]{2,3}'| tr '\n' ' ')
max=0
for t in ${temps}; do
  test "${t}" -gt "${max}" && max="${t}"
done
printf '%s' "${max}"
