#!/usr/bin/env sh

T1=$(cat /sys/class/net/wlp2s0/statistics/tx_bytes)
sleep 1
T2=$(cat /sys/class/net/wlp2s0/statistics/tx_bytes)
TBPS=$(expr $T2 - $T1)
TKBPS=$(expr $TBPS / 1024)

printf '%s' "${TKBPS}"
